version: "3"

services:
  web:
    container_name: dt_express
    build: .
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  mongo:
    container_name: dt_mongo
    image: mongo:5.0-focal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"